### ISSUE TITLE
Build goal fails with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by salmonb** [mP1/j2cl-maven-plugin#656]
hi,

I'm trying to migrate a GWT app to J2CL using your plugin for the first time, but I'm getting this error:

````
[DEBUG] Configuring mojo execution 'walkingkooka:j2cl-maven-plugin:1.0-SNAPSHOT:build:build-js' with basic configurator -->
[DEBUG]   (f) cache = /Users/bruno/IdeaProjects/webfx-kbs3-aggregate/webfx-demos-aggregate/webfx-demo-colorfulcircles/webfx-demo-colorfulcircles-application-j2cl/target/walkingkooka-j2cl-maven-plugin-cache
[DEBUG]   (f) classpathRequired = []
[DEBUG]   (f) classpathScope = compile
[DEBUG]   (f) compilationLevel = ADVANCED
[DEBUG]   (f) defines = {jre.checkedMode=DISABLED, jre.checks.checkLevel=MINIMAL, jsinterop.checks=DISABLED}
[DEBUG]   (f) entryPoints = [dev.webfx.platform.boot.spi.impl.gwt]
[DEBUG]   (f) externs = []
[DEBUG]   (f) formatting = [PRETTY_PRINT, PRINT_INPUT_DELIMITER, SINGLE_QUOTES]
[DEBUG]   (f) ignoredDependencies = [org.openjfx:*:*]
[DEBUG]   (f) initialScriptFilename = /Users/bruno/IdeaProjects/webfx-kbs3-aggregate/webfx-demos-aggregate/webfx-demo-colorfulcircles/webfx-demo-colorfulcircles-application-j2cl/target/webfx-demo-colorfulcircles-application-j2cl-0.1.0-SNAPSHOT/dev.webfx-webfx-demo-colorfulcircles-application-j2cl.js
[DEBUG]   (f) javaCompilerArguments = []
[DEBUG]   (f) javascriptSourceRequired = []
[DEBUG]   (f) languageOut = ECMASCRIPT_2016
[DEBUG]   (f) mavenProject = MavenProject: dev.webfx:webfx-demo-colorfulcircles-application-j2cl:0.1.0-SNAPSHOT @ /Users/bruno/IdeaProjects/webfx-kbs3-aggregate/webfx-demos-aggregate/webfx-demo-colorfulcircles/webfx-demo-colorfulcircles-application-j2cl/pom.xml
[DEBUG]   (f) mavenSession = org.apache.maven.execution.MavenSession@66c38e51
[DEBUG]   (f) output = /Users/bruno/IdeaProjects/webfx-kbs3-aggregate/webfx-demos-aggregate/webfx-demo-colorfulcircles/webfx-demo-colorfulcircles-application-j2cl/target/webfx-demo-colorfulcircles-application-j2cl-0.1.0-SNAPSHOT
[DEBUG]   (f) repositories = [webfx-snapshots (https://oss.sonatype.org/content/repositories/snapshots/, default, snapshots), gluon-repository (https://nexus.gluonhq.com/nexus/content/repositories/releases, default, releases), central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG]   (f) repositorySession = org.eclipse.aether.DefaultRepositorySystemSession@11c78080
[DEBUG]   (f) sourceMaps = sources/
[DEBUG]   (f) threadPoolSize = 0
[DEBUG] -- end configuration --
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.038 s
[INFO] Finished at: 2024-02-03T16:25:17Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal walkingkooka:j2cl-maven-plugin:1.0-SNAPSHOT:build (build-js) on project webfx-demo-colorfulcircles-application-j2cl: Failed to build project, check logs above: 'java.util.concurrent.ConcurrentMap walkingkooka.collect.map.Maps.concurrent()' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal walkingkooka:j2cl-maven-plugin:1.0-SNAPSHOT:build (build-js) on project webfx-demo-colorfulcircles-application-j2cl: Failed to build project, check logs above
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to build project, check logs above
    at walkingkooka.j2cl.maven.J2clMojoBuild.execute (J2clMojoBuild.java:53)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: java.lang.NoSuchMethodError: 'java.util.concurrent.ConcurrentMap walkingkooka.collect.map.Maps.concurrent()'
    at walkingkooka.j2cl.maven.J2clMavenMiddlewareImpl.<init> (J2clMavenMiddlewareImpl.java:95)
    at walkingkooka.j2cl.maven.J2clMavenMiddlewareImpl.with (J2clMavenMiddlewareImpl.java:52)
    at walkingkooka.j2cl.maven.J2clMavenMiddleware.of (J2clMavenMiddleware.java:41)
    at walkingkooka.j2cl.maven.J2clMojoBuildTestWatch.mavenMiddleware (J2clMojoBuildTestWatch.java:298)
    at walkingkooka.j2cl.maven.J2clMojoBuild.context (J2clMojoBuild.java:78)
    at walkingkooka.j2cl.maven.J2clMojoBuild.execute (J2clMojoBuild.java:37)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[DEBUG] Shutting down adapter factory; available factories [file-lock, rwlock-local, semaphore-local, noop]; available name mappers [discriminating, file-gav, file-hgav, file-static, gav, static]
[DEBUG] Shutting down 'file-lock' factory
[DEBUG] Shutting down 'rwlock-local' factory
[DEBUG] Shutting down 'semaphore-local' factory
[DEBUG] Shutting down 'noop' factory
````

Am I doing something wrong?

**Comment by mP1** [comment]
Hi..

No thats my mistake, let me try and push a fix...

```
Caused by: java.lang.NoSuchMethodError: 'java.util.concurrent.ConcurrentMap walkingkooka.collect.map.Maps.concurrent()'
    at walkingkooka.j2cl.maven.J2clMavenMiddlewareImpl.<init> (J2clMavenMiddlewareImpl.java:95)
```

**Comment by mP1** [comment]
Ive rebuilt and redeployed `j2cl-maven-plugin` this should fix the NoSuchMethodError you were seeing hopefully. Please delete the two local cached copies of `walkingkooka:walkingkooka.*` and `walkingkooka:j2cl-maven-plugin:*` just to be sure and try again.

**Comment by mP1** [comment]
Let me know how it goes.

**Comment by salmonb** [comment]
Thanks, your fixed worked and the NoSuchMethodError disappeared! 🎉

However the build still fails, but now for another reason:

````
[DEBUG] Loading mojo walkingkooka:j2cl-maven-plugin:1.0-SNAPSHOT:build from plugin realm ClassRealm[plugin>walkingkooka:j2cl-maven-plugin:1.0-SNAPSHOT, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7]
[DEBUG] Configuring mojo execution 'walkingkooka:j2cl-maven-plugin:1.0-SNAPSHOT:build:build-js' with basic configurator -->
[DEBUG]   (f) cache = /Users/bruno/IdeaProjects/webfx-kbs3-aggregate/webfx-demos-aggregate/webfx-demo-colorfulcircles/webfx-demo-colorfulcircles-application-j2cl/target/walkingkooka-j2cl-maven-plugin-cache
[DEBUG]   (f) classpathRequired = []
[DEBUG]   (f) classpathScope = compile
[DEBUG]   (f) compilationLevel = ADVANCED
[DEBUG]   (f) defines = {jre.checkedMode=DISABLED, jre.checks.checkLevel=MINIMAL, jsinterop.checks=DISABLED}
[DEBUG]   (f) entryPoints = [dev.webfx.platform.boot.spi.impl.gwt]
[DEBUG]   (f) externs = []
[DEBUG]   (f) formatting = [PRETTY_PRINT, PRINT_INPUT_DELIMITER, SINGLE_QUOTES]
[DEBUG]   (f) ignoredDependencies = [org.openjfx:*:*]
[DEBUG]   (f) initialScriptFilename = /Users/bruno/IdeaProjects/webfx-kbs3-aggregate/webfx-demos-aggregate/webfx-demo-colorfulcircles/webfx-demo-colorfulcircles-application-j2cl/target/webfx-demo-colorfulcircles-application-j2cl-0.1.0-SNAPSHOT/dev.webfx-webfx-demo-colorfulcircles-application-j2cl.js
[DEBUG]   (f) javaCompilerArguments = []
[DEBUG]   (f) javascriptSourceRequired = []
[DEBUG]   (f) languageOut = ECMASCRIPT_2016
[DEBUG]   (f) mavenProject = MavenProject: dev.webfx:webfx-demo-colorfulcircles-application-j2cl:0.1.0-SNAPSHOT @ /Users/bruno/IdeaProjects/webfx-kbs3-aggregate/webfx-demos-aggregate/webfx-demo-colorfulcircles/webfx-demo-colorfulcircles-application-j2cl/pom.xml
[DEBUG]   (f) mavenSession = org.apache.maven.execution.MavenSession@58496c97
[DEBUG]   (f) output = /Users/bruno/IdeaProjects/webfx-kbs3-aggregate/webfx-demos-aggregate/webfx-demo-colorfulcircles/webfx-demo-colorfulcircles-application-j2cl/target/webfx-demo-colorfulcircles-application-j2cl-0.1.0-SNAPSHOT
[DEBUG]   (f) repositories = [webfx-snapshots (https://oss.sonatype.org/content/repositories/snapshots/, default, snapshots), gluon-repository (https://nexus.gluonhq.com/nexus/content/repositories/releases, default, releases), central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG]   (f) repositorySession = org.eclipse.aether.DefaultRepositorySystemSession@40d848f9
[DEBUG]   (f) sourceMaps = sources/
[DEBUG]   (f) threadPoolSize = 0
[DEBUG] -- end configuration --
[DEBUG] Extension realms for project dev.webfx:webfx-demo-colorfulcircles-application:jar:0.1.0-SNAPSHOT: (none)
[DEBUG] Looking up lifecycle mappings for packaging jar from ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]]
[DEBUG] Extension realms for project dev.webfx:webfx-demo-colorfulcircles:pom:0.1.0-SNAPSHOT: (none)
[DEBUG] Looking up lifecycle mappings for packaging pom from ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]]
[DEBUG] Skipped remote request for dev.webfx:webfx-parent:0.1.0-SNAPSHOT/maven-metadata.xml locally installed metadata up-to-date
[DEBUG] Extension realms for project dev.webfx:webfx-parent:pom:0.1.0-SNAPSHOT: (none)
[DEBUG] Looking up lifecycle mappings for packaging pom from ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]]
[DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=117315, ConflictMarker.markTime=23704, ConflictMarker.nodeCount=1, ConflictIdSorter.graphTime=19579, ConflictIdSorter.topsortTime=8583, ConflictIdSorter.conflictIdCount=0, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=27681, ConflictResolver.conflictItemCount=0, DfDependencyCollector.collectTime=5573, DfDependencyCollector.transformTime=235296}
[DEBUG] dev.webfx:webfx-parent:pom:0.1.0-SNAPSHOT
[DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=13196, ConflictMarker.markTime=19680, ConflictMarker.nodeCount=1, ConflictIdSorter.graphTime=2442, ConflictIdSorter.topsortTime=8325, ConflictIdSorter.conflictIdCount=0, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=20867, ConflictResolver.conflictItemCount=0, DfDependencyCollector.collectTime=4407, DfDependencyCollector.transformTime=80850}
[DEBUG] dev.webfx:webfx-demo-colorfulcircles:pom:0.1.0-SNAPSHOT
[DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=125207, ConflictMarker.markTime=22193, ConflictMarker.nodeCount=9, ConflictIdSorter.graphTime=55566, ConflictIdSorter.topsortTime=75162, ConflictIdSorter.conflictIdCount=4, ConflictIdSorter.conflictIdCycleCount=2, ConflictResolver.totalTime=994753, ConflictResolver.conflictItemCount=5, DfDependencyCollector.collectTime=10070476, DfDependencyCollector.transformTime=1304273}
[DEBUG] dev.webfx:webfx-demo-colorfulcircles-application:jar:0.1.0-SNAPSHOT
[DEBUG]    org.openjfx:javafx-base:jar:19:provided
[DEBUG]       org.openjfx:javafx-base:jar:mac:19:provided
[DEBUG]    org.openjfx:javafx-graphics:jar:19:provided
[DEBUG]       org.openjfx:javafx-graphics:jar:mac:19:provided
[DEBUG] Extension realms for project org.openjfx:javafx-base:jar:19: (none)
[DEBUG] Looking up lifecycle mappings for packaging jar from ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]]
[DEBUG] Extension realms for project org.openjfx:javafx:pom:19: (none)
[DEBUG] Looking up lifecycle mappings for packaging pom from ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]]
[DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=15682, ConflictMarker.markTime=20291, ConflictMarker.nodeCount=1, ConflictIdSorter.graphTime=3099, ConflictIdSorter.topsortTime=5390, ConflictIdSorter.conflictIdCount=0, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=20819, ConflictResolver.conflictItemCount=0, DfDependencyCollector.collectTime=13795, DfDependencyCollector.transformTime=81138}
[DEBUG] org.openjfx:javafx:pom:19
[WARNING] Failed to build parent project for org.openjfx:javafx-base:jar:19
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id linux-x86_64 @ line 36, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id linux-aarch64 @ line 68, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id macosx-x86_64 @ line 116, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id macosx-aarch64 @ line 148, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id windows-x86_64 @ line 180, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id windows-x86 @ line 212, column 17
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:208)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:333)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:295)
    at org.apache.maven.project.DefaultProjectBuilder.initParent (DefaultProjectBuilder.java:911)
    at org.apache.maven.project.DefaultProjectBuilder.initProject (DefaultProjectBuilder.java:674)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:188)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:333)
    at walkingkooka.j2cl.maven.J2clMavenMiddlewareImpl.mavenProject0 (J2clMavenMiddlewareImpl.java:110)
    at walkingkooka.j2cl.maven.J2clMavenMiddlewareImpl.mavenProject (J2clMavenMiddlewareImpl.java:85)
    at walkingkooka.j2cl.maven.J2clArtifact.mavenProject (J2clArtifact.java:766)
    at walkingkooka.j2cl.maven.J2clArtifact.dependencyManagement (J2clArtifact.java:205)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies0 (J2clArtifact.java:258)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies0 (J2clArtifact.java:258)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.lambda$gather$0 (J2clArtifact.java:94)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherSubTask (J2clArtifact.java:171)
    at walkingkooka.j2cl.maven.J2clArtifact.gather (J2clArtifact.java:83)
    at walkingkooka.j2cl.maven.J2clMojoBuildTestWatch.gatherDependencies (J2clMojoBuildTestWatch.java:137)
    at walkingkooka.j2cl.maven.J2clMojoBuild.execute (J2clMojoBuild.java:43)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: org.apache.maven.model.building.ModelBuildingException: 6 problems were encountered while building the effective model for org.openjfx:javafx:19
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id linux-x86_64 @ line 36, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id linux-aarch64 @ line 68, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id macosx-x86_64 @ line 116, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id macosx-aarch64 @ line 148, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id windows-x86_64 @ line 180, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id windows-x86 @ line 212, column 17
    at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException (DefaultModelProblemCollector.java:176)
    at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:508)
    at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:410)
    at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:243)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:176)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:333)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:295)
    at org.apache.maven.project.DefaultProjectBuilder.initParent (DefaultProjectBuilder.java:911)
    at org.apache.maven.project.DefaultProjectBuilder.initProject (DefaultProjectBuilder.java:674)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:188)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:333)
    at walkingkooka.j2cl.maven.J2clMavenMiddlewareImpl.mavenProject0 (J2clMavenMiddlewareImpl.java:110)
    at walkingkooka.j2cl.maven.J2clMavenMiddlewareImpl.mavenProject (J2clMavenMiddlewareImpl.java:85)
    at walkingkooka.j2cl.maven.J2clArtifact.mavenProject (J2clArtifact.java:766)
    at walkingkooka.j2cl.maven.J2clArtifact.dependencyManagement (J2clArtifact.java:205)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies0 (J2clArtifact.java:258)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies0 (J2clArtifact.java:258)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.lambda$gather$0 (J2clArtifact.java:94)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherSubTask (J2clArtifact.java:171)
    at walkingkooka.j2cl.maven.J2clArtifact.gather (J2clArtifact.java:83)
    at walkingkooka.j2cl.maven.J2clMojoBuildTestWatch.gatherDependencies (J2clMojoBuildTestWatch.java:137)
    at walkingkooka.j2cl.maven.J2clMojoBuild.execute (J2clMojoBuild.java:43)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
[DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=20566, ConflictMarker.markTime=13272, ConflictMarker.nodeCount=3, ConflictIdSorter.graphTime=6357, ConflictIdSorter.topsortTime=18098, ConflictIdSorter.conflictIdCount=1, ConflictIdSorter.conflictIdCycleCount=1, ConflictResolver.totalTime=53857, ConflictResolver.conflictItemCount=1, DfDependencyCollector.collectTime=154827, DfDependencyCollector.transformTime=125836}
[DEBUG] org.openjfx:javafx-base:jar:19
[DEBUG]    org.openjfx:javafx-base:jar:mac:19:compile
[DEBUG] Extension realms for project org.openjfx:javafx-base:jar:19: (none)
[DEBUG] Looking up lifecycle mappings for packaging jar from ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]]
[DEBUG] Extension realms for project org.openjfx:javafx:pom:19: (none)
[DEBUG] Looking up lifecycle mappings for packaging pom from ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]]
[DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=15203, ConflictMarker.markTime=19676, ConflictMarker.nodeCount=1, ConflictIdSorter.graphTime=2469, ConflictIdSorter.topsortTime=5254, ConflictIdSorter.conflictIdCount=0, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=22445, ConflictResolver.conflictItemCount=0, DfDependencyCollector.collectTime=5152, DfDependencyCollector.transformTime=80578}
[DEBUG] org.openjfx:javafx:pom:19
[WARNING] Failed to build parent project for org.openjfx:javafx-base:jar:19
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id linux-x86_64 @ line 36, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id linux-aarch64 @ line 68, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id macosx-x86_64 @ line 116, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id macosx-aarch64 @ line 148, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id windows-x86_64 @ line 180, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id windows-x86 @ line 212, column 17
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:208)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:333)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:295)
    at org.apache.maven.project.DefaultProjectBuilder.initParent (DefaultProjectBuilder.java:911)
    at org.apache.maven.project.DefaultProjectBuilder.initProject (DefaultProjectBuilder.java:674)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:188)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:333)
    at walkingkooka.j2cl.maven.J2clMavenMiddlewareImpl.mavenProject0 (J2clMavenMiddlewareImpl.java:110)
    at walkingkooka.j2cl.maven.J2clMavenMiddlewareImpl.mavenProject (J2clMavenMiddlewareImpl.java:85)
    at walkingkooka.j2cl.maven.J2clArtifact.mavenProject (J2clArtifact.java:766)
    at walkingkooka.j2cl.maven.J2clArtifact.dependencyManagement (J2clArtifact.java:205)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies0 (J2clArtifact.java:258)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies0 (J2clArtifact.java:258)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies0 (J2clArtifact.java:258)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.lambda$gather$0 (J2clArtifact.java:94)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherSubTask (J2clArtifact.java:171)
    at walkingkooka.j2cl.maven.J2clArtifact.gather (J2clArtifact.java:83)
    at walkingkooka.j2cl.maven.J2clMojoBuildTestWatch.gatherDependencies (J2clMojoBuildTestWatch.java:137)
    at walkingkooka.j2cl.maven.J2clMojoBuild.execute (J2clMojoBuild.java:43)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: org.apache.maven.model.building.ModelBuildingException: 6 problems were encountered while building the effective model for org.openjfx:javafx:19
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id linux-x86_64 @ line 36, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id linux-aarch64 @ line 68, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id macosx-x86_64 @ line 116, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id macosx-aarch64 @ line 148, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id windows-x86_64 @ line 180, column 17
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id windows-x86 @ line 212, column 17
    at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException (DefaultModelProblemCollector.java:176)
    at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:508)
    at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:410)
    at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:243)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:176)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:333)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:295)
    at org.apache.maven.project.DefaultProjectBuilder.initParent (DefaultProjectBuilder.java:911)
    at org.apache.maven.project.DefaultProjectBuilder.initProject (DefaultProjectBuilder.java:674)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:188)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:333)
    at walkingkooka.j2cl.maven.J2clMavenMiddlewareImpl.mavenProject0 (J2clMavenMiddlewareImpl.java:110)
    at walkingkooka.j2cl.maven.J2clMavenMiddlewareImpl.mavenProject (J2clMavenMiddlewareImpl.java:85)
    at walkingkooka.j2cl.maven.J2clArtifact.mavenProject (J2clArtifact.java:766)
    at walkingkooka.j2cl.maven.J2clArtifact.dependencyManagement (J2clArtifact.java:205)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies0 (J2clArtifact.java:258)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies0 (J2clArtifact.java:258)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies0 (J2clArtifact.java:258)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherDependencies (J2clArtifact.java:201)
    at walkingkooka.j2cl.maven.J2clArtifact.lambda$gather$0 (J2clArtifact.java:94)
    at walkingkooka.j2cl.maven.J2clArtifact.gatherSubTask (J2clArtifact.java:171)
    at walkingkooka.j2cl.maven.J2clArtifact.gather (J2clArtifact.java:83)
    at walkingkooka.j2cl.maven.J2clMojoBuildTestWatch.gatherDependencies (J2clMojoBuildTestWatch.java:137)
    at walkingkooka.j2cl.maven.J2clMojoBuild.execute (J2clMojoBuild.java:43)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
[DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=28327, ConflictMarker.markTime=24033, ConflictMarker.nodeCount=3, ConflictIdSorter.graphTime=9779, ConflictIdSorter.topsortTime=34856, ConflictIdSorter.conflictIdCount=1, ConflictIdSorter.conflictIdCycleCount=1, ConflictResolver.totalTime=85473, ConflictResolver.conflictItemCount=1, DfDependencyCollector.collectTime=179765, DfDependencyCollector.transformTime=203489}
[DEBUG] org.openjfx:javafx-base:jar:19
[DEBUG]    org.openjfx:javafx-base:jar:mac:19:compile
````

It looks like this is the same reason as the build fail with the vertispan plugin (see [my issue](https://github.com/Vertispan/j2clmavenplugin/issues/252)).

I thought that I would have more chance with your plugin, as according to your README your plugin gives more control over the dependencies.

My case is that the module I want to compile with J2CL (let's call it module J) takes the source from another source module (let's call it module S) that has dependencies to OpenJFX (official implementation of JavaFX), but these dependencies are declared as `provided` in the pom.xml of module S. Module J wants to take only the application source code, not OpenJFX (which is not J2CL compatible), and instead compile it with an alternative implementation of JavaFX (through modules listed in the pom.xml of module J).

Unfortunately, it seems that both your plugin and the vertispan plugin are pulling the OpenJFX sources, despite they are not the ones that needs to be passed to J2CL in the end.

**Comment by mP1** [comment]
It’s complaining about some profile thing. That must be something to do
with your pom and usage of profiles. The plugin does is not profile aware,
it delegates resolving of all dependencies to maven itself.

mP

**Comment by mP1** [comment]
It’s complaining about Javafx. Not sure what your doing with javafx but
that’s never going to build in gwt or j2cl.

[DEBUG] org.openjfx:javafx:pom:19
[WARNING] Failed to build parent project for org.openjfx:javafx-base:jar:19
org.apache.maven.project.ProjectBuildingException: Some problems were
encountered while processing the POMs:
[ERROR] 'profiles.profile.id' must be unique but found duplicate
profile with id linux-x86_64 @ line 36, column 17
[ERROR] 'profiles.prof <http://profiles.profile.id>



mP

**Comment by salmonb** [comment]
Maybe I should clarify the context: I'm the author of [WebFX](https://github.com/webfx-project/webfx), a JavaFX transpiler.

I know that OpenJFX (the official implementation of JavaFX) is not compatible with GWT/J2CL, but WebFX (my alternative implementation of the JavaFX API) is compatible with GWT/J2CL.

The errors with profiles are in the OpenJFX modules, not the WebFX modules.
The issue here is that the plugin is pulling the OpenJFX modules instead of the WebFX modules.

WebFX actually aims for cross-platform development, so the web is not the only target platform, and that's why OpenJFX is still referenced in module S. But I try to compile module J for the web platform with your plugin, hoping that it will understand that it doesn't need to pull the OpenJFX modules (declared as provided in S), but instead pull the WebFX modules declared in J for the J2CL compilation.

Unfortunately, it is confused and is pulling the OpenJFX modules, so of course it fails.

**Comment by mP1** [comment]
Hi

Wow that sounds pretty cool. If u need any other help fee free to let me
know. I would suggest you join others in the gwt/j2cl community on gitter
in channels like vertispans/dominokit etc. sorry on my mobile can’t
remember the exact names…

mP

**Comment by mP1** [comment]
Regarding the pulling of the wrong javafx artifact that’s all maven, my
plugin leaves resolution of deps all up to maven so u need to fix the pom
first. I would suggest maven tree/dependency plugin will help you see the
tree view of exactly what deps are active for that pom setup.

mP

**Comment by mP1** [comment]
Here’s another idea maybe create your own dummy artifact with the same
packages as the can’t translate javafx jar and include in the root my
walking*.txt file the one that supports blacklisting packages and the
putting that jar file ahead of javafx jar itself.

Not really sure but this javafx-blacklisting jar will be ignored by
everything else’s and might just result in javafx being ignored by my j2cl
maven plugin for purposes of locating source files for j2cl building.

Another option is too repackage javafx and include the blacklisting file in
there and reference that rather than the real javafx.

Might be worth a try.

mP

**Comment by mP1** [comment]
Thanx Bruno, after our chats on gitter i believe this is solved so closing.
